apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.imageUploader.name }}
spec:
  replicas: {{ .Values.imageUploader.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.imageUploader.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.imageUploader.name }}
    spec:
      containers:
        - name: {{ .Values.imageUploader.containerName }}
          image: {{ .Values.imageUploader.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.imageUploader.containerPort }}
