apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
        - name: {{ .Values.kafka.containerName }}
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka:9092,OUTSIDE://localhost:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.zookeeper.name }}:2181
            - name: KAFKA_CREATE_TOPICS
              value: "baeldung:1:1"