apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}
spec:
  type: ClusterIP
  ports:
    - name: inside
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: outside
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: {{ .Values.kafka.name }}
