apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  selector:
    app: {{ .Values.zookeeper.name }}
