apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-scheduler
  template:
    metadata:
      labels:
        app: training-scheduler
    spec:
      containers:
        - name: training-scheduler
          image: localhost:5001/training-scheduler:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
