version: '3.8'
services:
  data-uploader:
    build: .
    image: data-uploader:latest
    ports:
      - "8080:8080"
      -
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    command: server /data
